version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: todo-swagger-ui
    environment:
      - SWAGGER_URL=./swagger.yml
      - SWAGGER_JSON=/swagger/swagger.yml
    ports:
      - 8081:8080
    volumes:
      - ./swagger/:/swagger
  api:
    container_name: todo-api
    build:
      context: ./backend
    command: reflex -r '\.go$$' -s -- sh -c 'go run main.go -port=1999'
    ports:
      - ${API_PORT:-1999}:1999
    volumes:
      - ./backend:/app
    working_dir: /app
