version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui-sample
    environment:
      - SWAGGER_URL=./swagger.yml
      - SWAGGER_JSON=/swagger/swagger.yml
    ports:
      - 8081:8080
    volumes:
      - ./swagger/:/swagger