version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_URL=./swagger.yml
      - SWAGGER_JSON=/swagger/swagger.yml
    ports:
      - 8080:8080
    volumes:
      - ./swagger/:/swagger
