swagger: "2.0"
info:
  version: "1.0.0"
  title: todo API
  description: todo
  contact:
    name: Haruki Ido
host: "localhost:1999"
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /todo:
    get:
      description: タスク一覧取得
      summary: index-todo
      tags:
        - Todo
      operationId: index-todo
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ListTodo"
          headers: {}
    post:
      description: タスク作成
      summary: create-todo
      tags:
        - Todo
      operationId: create-todo
      deprecated: false
      parameters:
        - name: body
          in: body
          required: false
          description: ""
          schema:
            $ref: "#/definitions/CreateTodoRequest"
      responses:
        "201":
          description: created
          schema:
            $ref: "#/definitions/CreateTodoResponse"

# スキーマの定義
definitions:
  Todo:
    properties:
      id:
        type: integer
      body:
        type: string
    required:
      - id
      - body
  ListTodo:
    title: IndexTodo
    type: object
    properties:
      todos:
        type: array
        items:
          $ref: "#/definitions/Todo"
  CreateTodoRequest:
    title: CreateTodoRequest
    type: object
    properties:
      body:
        type: string
    required:
      - body
  CreateTodoResponse:
    title: CreateTodoResponse
    type: object
    properties:
      id:
        type: integer
        format: int64
