// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateTodoResponse CreateTodoResponse
//
// swagger:model CreateTodoResponse
type CreateTodoResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this create todo response
func (m *CreateTodoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create todo response based on context it is used
func (m *CreateTodoResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTodoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTodoResponse) UnmarshalBinary(b []byte) error {
	var res CreateTodoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
